/**
 * JSON exporter (M5b).
 *
 * Exports the full project + all scenarios + the audit log as a single
 * JSON document. Useful for:
 *  - backup / restore of a project
 *  - sharing a complete model with a colleague
 *  - reproducing a bug with the same exact inputs
 *
 * No dependencies. Pure data-to-blob.
 */

import type { Project } from '@/types/project';
import type { Scenario } from '@/types/scenario';
import { readAudit, type AuditEntry } from '@/data/audit-log';

export interface JsonExportPayload {
  formatVersion: '1.0';
  exportedAt: string;
  app: {
    name: string;
    note: string;
  };
  project: Project;
  scenarios: Scenario[];
  audit: AuditEntry[];
}

export function buildJsonExport(
  project: Project,
  scenarios: Scenario[],
): JsonExportPayload {
  return {
    formatVersion: '1.0',
    exportedAt: new Date().toISOString(),
    app: {
      name: 'SOW Cost Calculator',
      note: 'Generated by Export Center (M5b). Importing this file is not yet supported.',
    },
    project,
    scenarios,
    audit: readAudit(project.id),
  };
}

/** Convert a payload to a Blob with `application/json` MIME type. */
export function jsonExportBlob(payload: JsonExportPayload): Blob {
  const text = JSON.stringify(payload, null, 2);
  return new Blob([text], { type: 'application/json' });
}

/** Convenience: build + serialize to a Blob in one call. */
export function exportProjectAsJson(
  project: Project,
  scenarios: Scenario[],
): Blob {
  return jsonExportBlob(buildJsonExport(project, scenarios));
}

/** Suggested filename based on the project name + date. */
export function jsonExportFilename(project: Project): string {
  const safeName = project.name.replace(/[^A-Za-z0-9_-]+/g, '_').slice(0, 60);
  const date = new Date().toISOString().slice(0, 10);
  return `${safeName}_${date}.json`;
}
