<#
.SYNOPSIS
    SOW Cost Calculator — Local Environment Bootstrap (PowerShell).

.DESCRIPTION
    Creates the project directory tree and optionally applies a sync manifest
    produced by Claude in a conversation. Idempotent: safe to re-run.

    Equivalent in behavior to scripts/bootstrap.py.

.PARAMETER Target
    Target directory. Default: ./sow-calculator

.PARAMETER Manifest
    Path to a sync manifest JSON to apply after init.

.PARAMETER Verify
    Check structure without modifying anything.

.EXAMPLE
    .\bootstrap.ps1
    .\bootstrap.ps1 -Target .\sow-calc
    .\bootstrap.ps1 -Manifest .\sync-manifest.json
    .\bootstrap.ps1 -Verify

.NOTES
    Requires PowerShell 5.1+ (Windows PowerShell) or PowerShell 7+ (cross-platform).
#>

[CmdletBinding()]
param(
    [string]$Target = "./sow-calculator",
    [string]$Manifest,
    [switch]$Verify
)

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Project structure — keep in sync with bootstrap.py
# ---------------------------------------------------------------------------

$ManifestVersion = "1.0"

$Directories = @(
    "docs",
    "docs/decisions",
    "docs/wireframes",
    "src",
    "src/engine",
    "src/engine/calculations",
    "src/data",
    "src/types",
    "src/ui",
    "src/ui/components",
    "src/ui/pages",
    "seed",
    "seed/rate-cards",
    "seed/cloud-pricing",
    "seed/scenarios",
    "scripts",
    "tests",
    "tests/engine",
    "tests/fixtures",
    ".sync"
)

$PlaceholderFiles = [ordered]@{
    "README.md" = "# SOW Cost Calculator`n`nGenerated by bootstrap.ps1. See docs/ for design deliverables.`n"
    "docs/00-prompt.md" = "<!-- Place the original SOW_Cost_Calculator_Prompt.md here. -->`n"
    "docs/01-clarifying-questions.md" = "<!-- Deliverable #1 -->`n"
    "docs/02-information-architecture.md" = "<!-- Deliverable #2 -->`n"
    "docs/03-data-model.md" = "<!-- Deliverable #3 -->`n"
    "docs/04-calculation-logic.md" = "<!-- Deliverable #4 -->`n"
    "docs/05-wireframes.md" = "<!-- Deliverable #5 -->`n"
    "docs/06-seed-data.md" = "<!-- Deliverable #6 -->`n"
    "docs/07-tech-stack.md" = "<!-- Deliverable #7 -->`n"
    "docs/08-phase1-build-plan.md" = "<!-- Deliverable #8 -->`n"
    "docs/09-risks-and-defensibility.md" = "<!-- Deliverable #9 -->`n"
    ".gitignore" = "node_modules/`ndist/`nbuild/`n.env`n.env.local`n*.log`n.DS_Store`n.sync/last-applied.json`n"
    ".sync/README.md" = "# Sync directory`n`nManaged by scripts/bootstrap.ps1. Tracks which manifest from Claude was last applied so we can diff state between conversations.`n"
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet("info", "ok", "warn", "err", "new")]
        [string]$Level = "info"
    )
    $icon = switch ($Level) {
        "ok"   { "[OK] " }
        "warn" { "[!]  " }
        "err"  { "[X]  " }
        "new"  { "[+]  " }
        default { "     " }
    }
    $color = switch ($Level) {
        "ok"   { "Green" }
        "warn" { "Yellow" }
        "err"  { "Red" }
        "new"  { "Cyan" }
        default { "Gray" }
    }
    Write-Host "$icon$Message" -ForegroundColor $color
}

function Get-FileSha256 {
    param([string]$Path)
    return (Get-FileHash -Path $Path -Algorithm SHA256).Hash.ToLower()
}

# Reusable, single source of truth: writes UTF-8 *without* BOM.
# PowerShell 5.1's `Set-Content -Encoding UTF8` writes a BOM, which breaks
# package.json, tsconfig.json, postcss.config.js, and any other file that
# `JSON.parse` or a JS parser tries to read directly.
function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function New-DirIfMissing {
    param([string]$Path)
    if (Test-Path -Path $Path -PathType Container) {
        return $false
    }
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
    return $true
}

function Write-FileIfAbsent {
    param([string]$Path, [string]$Content)
    if (Test-Path -Path $Path -PathType Leaf) {
        return $false
    }
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    Write-Utf8NoBom -Path $Path -Content $Content
    return $true
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

function Invoke-Init {
    param([string]$TargetPath)

    $resolved = (Resolve-Path -Path (Split-Path -Parent $TargetPath) -ErrorAction SilentlyContinue)
    if (-not (Test-Path $TargetPath)) {
        New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
    }
    $absTarget = (Resolve-Path $TargetPath).Path

    Write-Log "Initializing SOW Calculator project at: $absTarget"

    $createdDirs = 0
    foreach ($d in $Directories) {
        $full = Join-Path $TargetPath $d
        if (New-DirIfMissing -Path $full) {
            $createdDirs++
            Write-Log "created dir: $d" "new"
        }
    }

    $createdFiles = 0
    foreach ($key in $PlaceholderFiles.Keys) {
        $full = Join-Path $TargetPath $key
        if (Write-FileIfAbsent -Path $full -Content $PlaceholderFiles[$key]) {
            $createdFiles++
            Write-Log "created file: $key" "new"
        }
    }

    $state = [ordered]@{
        version         = $ManifestVersion
        initialized_at  = (Get-Date).ToUniversalTime().ToString("o")
        target          = $absTarget
        directories     = $Directories
    }
    $statePath = Join-Path $TargetPath ".sync/state.json"
    Write-Utf8NoBom -Path $statePath -Content ($state | ConvertTo-Json -Depth 4)

    Write-Log "done. $createdDirs dirs and $createdFiles files created." "ok"
    Write-Log "next: paste files from Claude into docs/ and src/, or run with -Manifest." "info"
    return 0
}

function Invoke-ApplyManifest {
    param([string]$TargetPath, [string]$ManifestPath)

    if (-not (Test-Path $ManifestPath)) {
        Write-Log "manifest not found: $ManifestPath" "err"
        return 1
    }

    try {
        $manifest = Get-Content -Path $ManifestPath -Raw | ConvertFrom-Json
    } catch {
        Write-Log "manifest is not valid JSON: $_" "err"
        return 1
    }

    if ($manifest.version -ne $ManifestVersion) {
        Write-Log "manifest version mismatch (expected $ManifestVersion, got $($manifest.version))" "warn"
    }

    if (-not $manifest.files) {
        Write-Log "manifest has no 'files' array" "err"
        return 1
    }

    $label = if ($manifest.label) { $manifest.label } else { "(unlabeled)" }
    Write-Log "applying manifest: $label — $($manifest.files.Count) files"

    $new = 0; $updated = 0; $skipped = 0
    foreach ($entry in $manifest.files) {
        if (-not $entry.path) {
            Write-Log "entry missing 'path'" "warn"
            continue
        }
        $rel = $entry.path
        $content = if ($null -ne $entry.content) { $entry.content } else { "" }
        $mode = if ($entry.mode) { $entry.mode } else { "overwrite" }

        $out = Join-Path $TargetPath $rel
        $parent = Split-Path -Parent $out
        if ($parent -and -not (Test-Path $parent)) {
            New-Item -ItemType Directory -Path $parent -Force | Out-Null
        }

        $existed = Test-Path $out -PathType Leaf
        if ($existed -and $mode -eq "skip-if-exists") {
            $skipped++
            Write-Log "skip (exists): $rel" "info"
            continue
        }

        Write-Utf8NoBom -Path $out -Content $content
        if ($existed) {
            $updated++
            Write-Log "updated: $rel" "ok"
        } else {
            $new++
            Write-Log "wrote:   $rel" "new"
        }
    }

    $applied = [ordered]@{
        applied_at       = (Get-Date).ToUniversalTime().ToString("o")
        manifest_label   = $manifest.label
        manifest_sha256  = Get-FileSha256 -Path $ManifestPath
        counts           = [ordered]@{ new = $new; updated = $updated; skipped = $skipped }
    }
    $appliedPath = Join-Path $TargetPath ".sync/last-applied.json"
    Write-Utf8NoBom -Path $appliedPath -Content ($applied | ConvertTo-Json -Depth 4)

    Write-Log "done. $new new, $updated updated, $skipped skipped." "ok"
    return 0
}

function Invoke-Verify {
    param([string]$TargetPath)

    if (-not (Test-Path $TargetPath)) {
        Write-Log "target does not exist: $TargetPath" "err"
        return 1
    }
    $abs = (Resolve-Path $TargetPath).Path
    Write-Log "verifying structure at: $abs"

    $missingDirs = @()
    foreach ($d in $Directories) {
        if (-not (Test-Path -Path (Join-Path $TargetPath $d) -PathType Container)) {
            $missingDirs += $d
        }
    }
    $missingFiles = @()
    foreach ($f in $PlaceholderFiles.Keys) {
        if (-not (Test-Path -Path (Join-Path $TargetPath $f) -PathType Leaf)) {
            $missingFiles += $f
        }
    }

    if ($missingDirs.Count -eq 0 -and $missingFiles.Count -eq 0) {
        Write-Log "structure intact." "ok"
        return 0
    }

    foreach ($d in $missingDirs) { Write-Log "missing dir: $d" "warn" }
    foreach ($f in $missingFiles) { Write-Log "missing file: $f" "warn" }
    Write-Log "run without -Verify to repair." "info"
    return 1
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if ($Verify) {
    exit (Invoke-Verify -TargetPath $Target)
}

$rc = Invoke-Init -TargetPath $Target
if ($rc -ne 0) { exit $rc }

if ($Manifest) {
    $rc = Invoke-ApplyManifest -TargetPath $Target -ManifestPath $Manifest
}

exit $rc
